### ISSUE TITLE
Dependency `twixie` not listed in setup.py

### ISSUE THREAD

**Issue by nilsvu** [mcoughlin/gwemlightcurves#72]
The `KNTable` module depends on `twixie`, but `setup.py` does not list it. My brief search only turned up https://github.com/nhydock/TWIXIE, which I assume is not the correct `twixie` :) Could you point me to the correct repository?

**Comment by mcoughlin** [comment]
Ok I just moved the import inside the function it is used. It is on git.ligo.org if you have access to that, otherwise it isnt needed for core functionality.

**Comment by nilsvu** [comment]
Thank you @mcoughlin :)
