### ISSUE TITLE
Bu2019rp model missing in KNModels/io

### ISSUE THREAD

**Issue by nilsvu** [mcoughlin/gwemlightcurves#78]
Hi @mcoughlin, with your recent commit e35017bece22e8dff865bd25f91963b87e4080e7 you added these lines:

https://github.com/mcoughlin/gwemlightcurves/blob/master/gwemlightcurves/KNModels/io/__init__.py#L44

They expect the files `Bu2019rp.py` and `Bu2019rps.py` be present in `KNModels/io`, but they are missing. Did you perhaps not commit them?

**Comment by mcoughlin** [comment]
@nilsleiffischer argh! thanks, fixed!
