### ISSUE TITLE
Bug with calc_radius for lalsim TOV

### ISSUE THREAD

**Issue by asb5468** [mcoughlin/gwemlightcurves#85]
Hi, I was trying to follow along the example in the docs, but I'm getting a couple different errors when running this line `t_sly_lalsim = t.calc_radius(EOS='sly', TOV='lalsim')`
```
Traceback (most recent call last):
  File "calc_lightcurve.py", line 7, in <module>
    t_sly_lalsim = t.calc_radius(EOS='sly', TOV='lalsim')
  File "/home/sylvia.biscoveanu/.conda/envs/bilby1.0/lib/python3.7/site-packages/gwemlightcurves/KNModels/table.py", line 700, in calc_radius
    radius_of_mass_const = ms.interpolate(MassRadiusBaryMassTable['mass'], MassRadiusBaryMassTable['radius'])
UnboundLocalError: local variable 'ms' referenced before assignment
```
I think this is due to the fact that there is a missing import of
```
 import gwemlightcurves.EOS.TOV.Monica.MonotonicSpline as ms
 import gwemlightcurves.EOS.TOV.Monica.eos_tools as et
```
after this line https://github.com/mcoughlin/gwemlightcurves/blob/214572ad45a8401cbb121dfe5851c4c727d1e1e9/gwemlightcurves/KNModels/table.py#L698 Alternatively, if I set `polytrope=True`, I get the following error:
```
  File "calc_lightcurve.py", line 7, in <module>
    t_sly_lalsim = t.calc_radius(EOS='sly', TOV='lalsim', polytrope=True)
  File "/home/sylvia.biscoveanu/.conda/envs/bilby1.0/lib/python3.7/site-packages/gwemlightcurves/KNModels/table.py", line 694, in calc_radius
    ns_eos, eos_fam=construct_eos_from_polytrope(EOS)
  File "/home/sylvia.biscoveanu/.conda/envs/bilby1.0/lib/python3.7/site-packages/gwemlightcurves/KNModels/table.py", line 140, in construct_eos_from_polytrope
    eos_indx=np.where(polytrope_table['eos']==eos)[0][0]
UnboundLocalError: local variable 'eos' referenced before assignment
```
I think this error is due to this line https://github.com/mcoughlin/gwemlightcurves/blob/214572ad45a8401cbb121dfe5851c4c727d1e1e9/gwemlightcurves/KNModels/table.py#L140 where `eos` should be replaced by `eos_names`.

**Comment by mcoughlin** [comment]
@asb5468 thanks for the heads up. Your assessment makes sense, want to submit a pull request?

**Comment by asb5468** [comment]
> @asb5468 thanks for the heads up. Your assessment makes sense, want to submit a pull request?

Yep, happy to submit a pull request if you think the diagnosis is correct!

**Comment by mcoughlin** [comment]
@asb5468 yes we don't use individual EOS calculations much anymore, so not surprised something got lost in translation.

**Comment by mcoughlin** [comment]
Thanks @asb5468 !
